import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: 'tests/e2e',
  testMatch: process.env.SABLE_E2E_MATCH ?? [
    'timeline-stability.spec.ts',
    'timeline-gap.spec.ts',
    'timeline-keyboard.spec.ts',
    'timeline-lifecycle.spec.ts',
    'timeline-media.spec.ts',
    'timeline-media-hold.spec.ts',
    'timeline-receipts.spec.ts',
    'window-activity.spec.ts',
    'timeline-notified.spec.ts',
    'timeline-unread.spec.ts',
    'timeline-row-height.spec.ts',
    'timeline-name-overflow.spec.ts',
    'timeline-content-overflow.spec.ts',
    'composer-alignment.spec.ts',
    'composer-wrapping.spec.ts',
    'composer-scheduling.spec.ts',
    'composer-send-failure.spec.ts',
    'composer-autocomplete.spec.ts',
    'composer-paste.spec.ts',
    'composer-markdown.spec.ts',
    'emote-board-glyphs.spec.ts',
    'account-mobile.spec.ts',
    'settings-size.spec.ts',
    'theme-catalog.spec.ts',
    'theme-variables.spec.ts',
    'avatar-frame.spec.ts',
    'settings-range.spec.ts',
    'reaction-sheet.spec.ts',
    'overlay-stacking.spec.ts',
    'profile-mobile.spec.ts',
    'room-settings-mobile.spec.ts',
    'room-settings-context.spec.ts',
    'mobile-drawer.spec.ts',
    'settings-slide.spec.ts',
    'profile-card-tint.spec.ts',
    'profile-card-status.spec.ts',
    'reply-name-color.spec.ts',
    'thread-panel.spec.ts',
    'thread-actions.spec.ts',
    'settings-backdrop.spec.ts',
    'sheet-swipe.spec.ts',
    'voice-room-chat.spec.ts',
    'calendar-room-menu.spec.ts',
    'room-icon-badge.spec.ts',
    'space-search-navigation.spec.ts',
    'space-timeline-navigation.spec.ts',
    'verification-qr.spec.ts',
    'onboarding.spec.ts',
  ],
  workers: 1,
  timeout: 60_000,
  use: { baseURL: 'http://127.0.0.1:4175', contextOptions: { reducedMotion: 'reduce' } },
  projects: [
    { name: 'chromium', grepInvert: /mobile/, use: devices['Desktop Chrome'] },
    {
      name: 'firefox',
      grepInvert: /mobile/,
      use: { ...devices['Desktop Firefox'], hasTouch: true },
    },
    { name: 'webkit', grepInvert: /mobile/, use: devices['Desktop Safari'] },
    {
      name: 'android',
      grep: /mobile|touch|the reveal/,
      use: { ...devices['Pixel 7'], browserName: 'chromium' },
    },
    {
      name: 'ios',
      grep: /mobile|touch|the reveal/,
      use: { ...devices['iPhone 13'], browserName: 'webkit' },
    },
  ],
  webServer: {
    command: 'pnpm exec vite dev --host 127.0.0.1 --port 4175 --strictPort',
    url: 'http://127.0.0.1:4175',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
