[package]
name = "sable-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sable-core = { path = "../sable-core", version = "0.1.0" }
async-trait = "0.1"
serde_json = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
console_error_panic_hook = "0.1"
tokio = { version = "1", default-features = false, features = ["sync"] }
tracing.workspace = true
tracing-web = "0.1.3"
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lints]
workspace = true
